# Generated by Django 3.2.3 on 2021-06-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientRequest',
        ),
    ]
