# Generated by Django 3.2.3 on 2021-06-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_delete_clientrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
