# Generated by Django 3.2.3 on 2021-06-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_watchman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchman',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
