# Generated by Django 3.2.3 on 2021-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_watchman_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchman',
            name='status',
        ),
    ]
