# Generated by Django 3.2.3 on 2021-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210610_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='watchman',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
