# Generated by Django 3.2.3 on 2021-06-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210610_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchman',
        ),
    ]
