# Generated by Django 3.2.3 on 2021-06-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretary', '0019_delete_watchman'),
        ('members', '0007_delete_watchman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(default='media\\images\\default.png', upload_to='media\\images')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('aboutme', models.TextField(blank=True, max_length=500)),
                ('work', models.CharField(blank=True, max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.user')),
            ],
        ),
    ]
