# Generated by Django 3.2 on 2021-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_watchman'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchman',
            name='blood_grp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='watchman',
            name='marrial_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='watchman',
            name='vechicle_deatails',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
