# Generated by Django 3.2 on 2021-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210614_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchman',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
