# Generated by Django 3.2.3 on 2021-06-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0002_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairman',
            old_name='experience',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='chairman',
            old_name='specialities',
            new_name='work',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='internship',
        ),
        migrations.AddField(
            model_name='members',
            name='work',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
