# Generated by Django 3.2.3 on 2021-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0005_remove_chairman_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='profile_pic',
            field=models.FileField(default='media\\images\\default.png', upload_to='media\\images'),
        ),
    ]
