# Generated by Django 3.2.3 on 2021-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0006_chairman_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_pic',
            field=models.FileField(default='media\\images\\d.png', upload_to='media\\images'),
        ),
        migrations.AlterField(
            model_name='members',
            name='profile_pic',
            field=models.FileField(default='media\\images\\d.png', upload_to='media\\images'),
        ),
    ]
