# Generated by Django 3.2.3 on 2021-06-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0007_auto_20210602_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
