# Generated by Django 3.2.3 on 2021-06-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0008_members_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_pic',
            field=models.FileField(default='media\\images\\default.png', upload_to='media\\images'),
        ),
        migrations.AlterField(
            model_name='members',
            name='profile_pic',
            field=models.FileField(default='media\\images\\default.png', upload_to='media\\images'),
        ),
    ]
