# Generated by Django 3.2.3 on 2021-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0009_auto_20210607_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='state',
        ),
        migrations.AddField(
            model_name='members',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='blood_grp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='family_members',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='house_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='job_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='marrial_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='vechicle_deatails',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
