# Generated by Django 3.2.3 on 2021-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0010_auto_20210610_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
