# Generated by Django 3.2.3 on 2021-06-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0012_myfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='o_r',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='myfamily',
            name='o_r',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
