# Generated by Django 3.2.3 on 2021-06-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0013_auto_20210611_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfamily',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myfamily',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myfamily',
            name='country',
        ),
    ]
