# Generated by Django 3.2.3 on 2021-06-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0014_auto_20210611_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfamily',
            name='state',
        ),
    ]
