# Generated by Django 3.2.3 on 2021-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0015_remove_myfamily_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfamily',
            name='o_r',
        ),
    ]
