# Generated by Django 3.2.3 on 2021-06-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0016_remove_myfamily_o_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditMyfamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(default='media\\images\\default.png', upload_to='media\\images')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('aboutme', models.TextField(blank=True, max_length=500)),
                ('work', models.CharField(blank=True, max_length=20)),
                ('job_address', models.CharField(blank=True, max_length=200)),
                ('blood_grp', models.CharField(blank=True, max_length=200)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.user')),
            ],
        ),
    ]
