# Generated by Django 3.2.3 on 2021-06-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0018_watchman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchman',
        ),
    ]
