# Generated by Django 3.2 on 2021-06-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0020_noticeboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='media\\images'),
        ),
    ]
