# Generated by Django 3.2 on 2021-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0021_alter_chairman_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_pic',
            field=models.FileField(default='media\\images\\default.png', upload_to='media\\images'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='media\\images'),
        ),
    ]
