# Generated by Django 3.2.3 on 2021-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0024_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
